spring.application.name=Bai1
spring.datasource.url=jdbc:mysql://localhost:3306/basic_auth_db
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.show_sql=true
spring.sql.init.mode=always
spring.jpa.properties.hibernate.hbm2ddl.auto=none